/**
 * Chooses the Noto font pieces a PDF needs for its text.
 *
 * The PDF is set in Noto Serif (with Noto Sans SC/JP/KR for CJK). Fontsource
 * splits each font into pieces ("subsets") by character range, served from
 * jsDelivr; only the pieces whose characters actually appear are used, so a
 * Latin-only NDA needs just the Noto Serif "latin" piece and a Japanese name
 * adds a few small CJK pieces. manifest.json is generated by
 * scripts/generate-font-manifest.mjs (npm run gen:fonts).
 */
import { distinctChars, inRanges, type Range } from "./chars";
import manifest from "./manifest.json";

interface Subset {
  name: string;
  ranges: Range[];
  /** SRI hash by variant, e.g. { "400-normal": "sha256-..." }. */
  files: Record<string, string>;
}

interface FontPackage {
  package: string;
  subsets: Subset[];
}

export type CjkLanguage = "sc" | "jp" | "kr";

/** One font file of a family, as react-pdf registers it. */
export interface FontFile {
  url: string;
  /** Subresource Integrity hash the downloaded file must match. */
  integrity: string;
  fontWeight?: number;
  fontStyle?: "normal" | "italic";
}

/** A font family to register with react-pdf. */
export interface PdfFont {
  family: string;
  files: FontFile[];
}

export interface FontPlan {
  /** Families in fallback order; the first is the primary text font. */
  fonts: PdfFont[];
  /** Characters no available font can draw (they won't appear in the PDF). */
  unsupported: string[];
}

// JSON imports type ranges as number[][]; the generator guarantees pairs.
const SERIF = manifest.serif as unknown as FontPackage;
const CJK = manifest.cjk as unknown as Record<CjkLanguage, FontPackage>;

function fontFile(
  { package: pkg }: FontPackage,
  subset: Subset,
  variant: string,
  style: Pick<FontFile, "fontWeight" | "fontStyle">,
): FontFile {
  return {
    url: `${manifest.baseUrl}/${pkg}@${manifest.version}/files/${pkg}-${subset.name}-${variant}.woff`,
    integrity: subset.files[variant],
    ...style,
  };
}

const serifFont = (subset: Subset): PdfFont => ({
  family: `${SERIF.package}-${subset.name}`,
  files: [
    fontFile(SERIF, subset, "400-normal", { fontWeight: 400 }),
    fontFile(SERIF, subset, "700-normal", { fontWeight: 700 }),
    fontFile(SERIF, subset, "400-italic", { fontStyle: "italic" }),
  ],
});

// CJK fonts have no italic; react-pdf resolves every family for every style
// in use, so register the regular face as italic too. Bold falls back to 400.
const cjkFont = (pkg: FontPackage, subset: Subset): PdfFont => ({
  family: `${pkg.package}-${subset.name}`,
  files: [
    fontFile(pkg, subset, "400-normal", { fontWeight: 400 }),
    fontFile(pkg, subset, "400-normal", { fontStyle: "italic" }),
  ],
});

/**
 * CJK fonts disagree on glyph shapes for shared Han characters, so pick the
 * language the text most likely is: kana means Japanese, Hangul means Korean,
 * otherwise Chinese.
 */
export function cjkPreference(text: string): CjkLanguage[] {
  if (/[\p{Script=Hiragana}\p{Script=Katakana}]/u.test(text)) return ["jp", "sc", "kr"];
  if (/\p{Script=Hangul}/u.test(text)) return ["kr", "jp", "sc"];
  return ["sc", "jp", "kr"];
}

const findSubset = (pkg: FontPackage, codePoint: number) =>
  pkg.subsets.find((subset) => inRanges(subset.ranges, codePoint));

/** Works out which font pieces are needed to draw `texts`. */
export function planFonts(texts: string[]): FontPlan {
  const chars = distinctChars(texts);
  const preference = cjkPreference(chars.join(""));
  const needed = new Set<Subset>([SERIF.subsets[0]]); // latin: the primary face
  const unsupported: string[] = [];

  for (const char of chars) {
    const codePoint = char.codePointAt(0)!;
    let subset = findSubset(SERIF, codePoint);
    for (const lang of preference) {
      if (subset) break;
      subset = findSubset(CJK[lang], codePoint);
    }
    if (subset) needed.add(subset);
    else unsupported.push(char);
  }

  // Manifest order, then CJK by preference, so the font stack is stable.
  const fonts = [
    ...SERIF.subsets.filter((s) => needed.has(s)).map(serifFont),
    ...preference.flatMap((lang) =>
      CJK[lang].subsets.filter((s) => needed.has(s)).map((s) => cjkFont(CJK[lang], s)),
    ),
  ];
  return { fonts, unsupported };
}
